### DISCUSSION TITLE
git is not installed in your root environment or as a build requirement.

### DISCUSSION THREAD

**Discussion by mxmlnkn** [fcakyon/conda-publish-action#9] [Q&A]
I tried the basic example from the description:

```yaml
[...]
jobs:
  Build-Conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Conda Packages
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda'
        platforms: 'win osx linux'
```

and got:

```
Run fcakyon/conda-publish-action@v1.3
  with:
    subdir: conda
    platforms: win osx linux
/usr/bin/docker run --name b361e87d3c3b02ed642c188c7d2697ee6985f_9a3560 --label 7b361e --workdir /github/workspace --rm -e INPUT_SUBDIR -e INPUT_PLATFORMS -e INPUT_ANACONDATOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/indexed_bzip2/indexed_bzip2":"/github/workspace" 7b361e:87d3c3b02ed642c188c7d2697ee6985f
+ set -o pipefail
+ check_if_setup_file_exists
+ '[' '!' -f setup.py ']'
+ go_to_build_dir
+ '[' '!' -z conda ']'
+ cd conda
+ check_if_meta_yaml_file_exists
+ '[' '!' -f meta.yaml ']'
+ build_package
+ conda build -c conda-forge -c pytorch -c fcakyon --output-folder . .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Error: git is not installed in your root environment or as a build requirement.
```
